### ISSUE TITLE
C4 hover tooltip wrong when holding a Defuser

### ISSUE THREAD

**Issue by a7f3** [TTT-2/TTT2#1161]
## Your version of TTT2 (mandatory)
- Latest GitHub version

## Describe the bug (mandatory)
While holding the Defuser over a C4 the hover tooltip says "Press [E] to use defuser" but you actually have to Primary click on the C4 to use the Defuser

## To reproduce
Hold Defuser pointing at C4

## Expected behaviour
Change the "[E]" to be whatever Primary click is.

## Context (please provide as much as you can)
![20231212002835_1](https://github.com/TTT-2/TTT2/assets/124642739/d18d4c0c-5a65-4782-a011-8a089a194f39)
![20231212002840_1](https://github.com/TTT-2/TTT2/assets/124642739/672c6266-9851-4d1c-9481-f00cf882c88e)

**Comment by TimGoll** [comment]
Good catch. Also the helpbox still uses HudHelp instead of TTT2HudHelp

**Comment by a7f3** [comment]
> Good catch. Also the helpbox still uses HudHelp instead of TTT2HudHelp

Oh that makes sense, was wondering why there was a hud without the file being included in the ttt2 repo

**Comment by EntranceJew** [comment]
fyi this is fixed in #1198 
![image](https://github.com/TTT-2/TTT2/assets/5711436/e83fcd64-b90f-4c1f-84a4-1f96e0ae785a)

**Comment by TimGoll** [comment]
> fyi this is fixed in #1198 ![image](https://private-user-images.githubusercontent.com/5711436/291608518-e83fcd64-b90f-4c1f-84a4-1f96e0ae785a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTkwMjMsIm5iZiI6MTcwMjk5ODcyMywicGF0aCI6Ii81NzExNDM2LzI5MTYwODUxOC1lODNmY2Q2NC1iOTBmLTRjMWYtODRhNC0xZjk2ZTBhZTc4NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTUxMjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAxY2Q1NWVhOTNkOGFjMWI1YTVjNTk1ZDQzZjJhYzMzOGRmOTRiZWI4MDgxM2MxY2E5OGYzOTc0ZTFkYzY2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oPnLsP5bjM-wNBM_FvHo3i5rDINrJEyqk0_pVN66ToE)

I think you misunderstood as this is not fixed. At least how I understood things

**Comment by EntranceJew** [comment]
You're right; I was moving it around and saw the huge `MOUSE1` and the other text didn't even register for me 😰
